// Methods
export const METHOD_GET = 'GET';
export const METHOD_POST = 'POST';
export const METHOD_DELETE = 'DELETE';

// Get All Rooms
export const GET_ALL_ROOMS_PENDING = 'GET_ALL_ROOMS_PENDING';
export const GET_ALL_ROOMS_FULFILLED = 'GET_ALL_ROOMS_FULFILLED';
export const GET_ALL_ROOMS_REJECTED = 'GET_ALL_ROOMS_REJECTED';

// Post Rooms
export const POST_ROOM_PENDING = 'POST_ROOM_PENDING';
export const POST_ROOM_FULFILLED = 'POST_ROOM_FULFILLED';
export const POST_ROOM_REJECTED = 'POST_ROOM_REJECTED';

// Get All Customers
export const GET_ALL_CUSTOMERS_PENDING = 'GET_ALL_CUSTOMERS_PENDING';
export const GET_ALL_CUSTOMERS_FULFILLED = 'GET_ALL_CUSTOMERS_FULFILLED';
export const GET_ALL_CUSTOMERS_REJECTED = 'GET_ALL_CUSTOMERS_REJECTED';

// Post Customer
export const POST_CUSTOMERS_PENDING = 'POST_CUSTOMERS_PENDING';
export const POST_CUSTOMERS_FULFILLED = 'POST_CUSTOMERS_FULFILLED';
export const POST_CUSTOMERS_REJECTED = 'POST_CUSTOMERS_REJECTED';
