// Methods
export const METHOD_GET = 'GET';
export const METHOD_POST = 'POST';
export const METHOD_DELETE = 'DELETE';
export const METHOD_PUT = 'PUT';

// Get All Rooms
export const GET_ALL_ROOMS_PENDING = 'GET_ALL_ROOMS_PENDING';
export const GET_ALL_ROOMS_FULFILLED = 'GET_ALL_ROOMS_FULFILLED';
export const GET_ALL_ROOMS_REJECTED = 'GET_ALL_ROOMS_REJECTED';

// Post Rooms
export const POST_ROOM_PENDING = 'POST_ROOM_PENDING';
export const POST_ROOM_FULFILLED = 'POST_ROOM_FULFILLED';
export const POST_ROOM_REJECTED = 'POST_ROOM_REJECTED';

// Put Rooms / Update Rooms
export const PUT_ROOM_PENDING = 'PUT_ROOM_PENDING';
export const PUT_ROOM_FULFILLED = 'PUT_ROOM_FULFILLED';
export const PUT_ROOM_REJECTED = 'PUT_ROOM_REJECTED';

// Get All Customers
export const GET_ALL_CUSTOMERS_PENDING = 'GET_ALL_CUSTOMERS_PENDING';
export const GET_ALL_CUSTOMERS_FULFILLED = 'GET_ALL_CUSTOMERS_FULFILLED';
export const GET_ALL_CUSTOMERS_REJECTED = 'GET_ALL_CUSTOMERS_REJECTED';

// Post Customer
export const POST_CUSTOMERS_PENDING = 'POST_CUSTOMERS_PENDING';
export const POST_CUSTOMERS_FULFILLED = 'POST_CUSTOMERS_FULFILLED';
export const POST_CUSTOMERS_REJECTED = 'POST_CUSTOMERS_REJECTED';

// Put Customer
export const PUT_CUSTOMERS_PENDING = 'PUT_CUSTOMERS_PENDING';
export const PUT_CUSTOMERS_FULFILLED = 'PUT_CUSTOMERS_FULFILLED';
export const PUT_CUSTOMERS_REJECTED = 'PUT_CUSTOMERS_REJECTED';

// Get ALL Checkin
export const GET_ALL_CHECKIN_PENDING = 'GET_ALL_CHECKIN_PENDING';
export const GET_ALL_CHECKIN_FULFILLED = 'GET_ALL_CHECKIN_FULFILLED';
export const GET_ALL_CHECKIN_REJECTED = 'GET_ALL_CHECKIN_REJECTED';

// Post Checkin
export const POST_CHECKIN_PENDING = 'POST_CHECKIN_PENDING';
export const POST_CHECKIN_FULFILLED = 'POST_CHECKIN_FULFILLED';
export const POST_CHECKIN_REJECTED = 'POST_CHECKIN_REJECTED';

// Put Checkin
export const PUT_CHECKIN_PENDING = 'PUT_CHECKIN_PENDING';
export const PUT_CHECKIN_FULFILLED = 'PUT_CHECKIN_FULFILLED';
export const PUT_CHECKIN_REJECTED = 'PUT_CHECKIN_REJECTED';
